name = "reveal"
license = "MIT"
licenselink = "https://github.com/heavywatal/hugo-theme-reveal/blob/master/LICENSE"
description = "Hugo theme for reveal.js and remark"
homepage = "https://github.com/heavywatal/hugo-theme-reveal/"
tags = ["presentation", "slide", "revealjs", "remark"]
features = []
min_version = 0.55.1

[author]
  name = "heavywatal"
  homepage = "https://heavywatal.github.io"
