name = "reveal"
license = "MIT"
licenselink = "https://github.com/heavywatal/hugo-theme-reveal/blob/master/LICENSE"
description = "Hugo theme for reveal.js"
homepage = "https://github.com/heavywatal/hugo-theme-reveal"
demosite = "https://heavywatal.github.io/slides/"
tags = ["presentation", "slide", "revealjs"]
features = []

[author]
  name = "heavywatal"
  homepage = "https://heavywatal.github.io"
